version: "3.8"
services:
  app:
    container_name: planner
    build: ./
    ports:
      - "8000:3000"
    volumes:
      - .:/planner
  db:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
